// src/app/layout.js
import { Geist, Geist_Mono, Lobster } from "next/font/google"; // 1. Lobster ফন্ট ইম্পোর্ট
import "./globals.css";
import Navbar from "../components/Navbar"; // 2. Navbar কম্পোনেন্ট ইম্পোর্ট

// Geist Sans ফন্ট কনফিগারেশন
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Geist Mono ফন্ট কনফিগারেশন
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 3. Lobster ফন্ট কনফিগারেশন (লোগোর জন্য)
const lobster = Lobster({
  weight: "400", // Lobster এর শুধু 400 weight থাকে
  subsets: ["latin"],
  variable: "--font-lobster", // এই ভেরিয়েবল নাম দিয়ে আমরা Navbar এ ফন্ট ডাকবো
});

export const metadata = {
  title: "Subnex - Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lobster.variable} antialiased`}
      >
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}